# Generated by Django 3.2.4 on 2021-08-25 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=12, null=True)),
                ('course_code', models.CharField(max_length=12, null=True)),
                ('syllabus', models.CharField(max_length=12, null=True)),
                ('Course_trainer', models.CharField(max_length=13, null=True)),
                ('Course_schedule', models.DateField(null=True)),
                ('course_duration', models.CharField(max_length=10, null=True)),
            ],
        ),
    ]
