# Generated by Django 3.2.4 on 2021-09-01 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='Course_schedule',
            new_name='course_schedule',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='Course_trainer',
            new_name='course_trainer',
        ),
        migrations.AlterField(
            model_name='course',
            name='course_duration',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
