# Generated by Django 3.2.4 on 2021-08-25 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=12, null=True)),
                ('last_name', models.CharField(max_length=12, null=True)),
                ('course', models.CharField(max_length=12, null=True)),
                ('gender', models.CharField(choices=[('F', 'Male'), ('F', 'Female'), ('F', 'Others')], max_length=1, null=True)),
                ('number_of_lessons', models.PositiveBigIntegerField(null=True)),
                ('profile', models.ImageField(null=True, upload_to='images/% Y/% m/% d/')),
                ('occupation', models.CharField(max_length=25, null=True)),
                ('phone_number', models.CharField(max_length=10, null=True)),
                ('bio', models.TextField(null=True)),
                ('cv', models.FileField(null=True, upload_to='')),
                ('email', models.EmailField(max_length=254, null=True)),
                ('contract', models.FileField(null=True, upload_to='')),
                ('date_hired', models.DateField(max_length=10, null=True)),
                ('language', models.CharField(choices=[('E', 'English'), ('E', 'Swahili'), ('E', 'Kinyarwanda'), ('E', 'French'), ('E', 'Kiganda')], max_length=1, null=True)),
            ],
        ),
    ]
