# Generated by Django 3.2.4 on 2021-08-25 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=12, null=True)),
                ('last_name', models.CharField(max_length=12, null=True)),
                ('age', models.PositiveSmallIntegerField(null=True)),
                ('date_of_birth', models.DateField(max_length=10, null=True)),
                ('roll_number', models.CharField(max_length=10, null=True)),
                ('student_email', models.EmailField(max_length=25, null=True)),
                ('nationality', models.CharField(choices=[('K', 'Kenya'), ('U', 'Uganda'), ('R', 'Rwanda')], max_length=23, null=True)),
                ('sudent_id', models.CharField(max_length=18, null=True)),
                ('id_number', models.CharField(max_length=18, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], max_length=6, null=True)),
                ('phone_number', models.CharField(max_length=16, null=True)),
                ('county', models.CharField(max_length=12, null=True)),
                ('profile', models.ImageField(null=True, upload_to='')),
                ('medical_report', models.FileField(null=True, upload_to='')),
                ('date_of_enrollment', models.DateField(max_length=8, null=True)),
                ('course_name', models.CharField(max_length=10, null=True)),
                ('language', models.CharField(choices=[('E', 'uenglish'), ('k', 'ukiswahili'), ('ki', 'ukinywaranda')], max_length=6, null=True)),
                ('serial_number', models.CharField(max_length=10, null=True)),
            ],
        ),
    ]
