# Generated by Django 3.2.4 on 2021-09-01 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='language',
            field=models.CharField(choices=[('E', 'uEnglish'), ('k', 'uKiswahili'), ('ki', 'uKinywaranda')], max_length=6, null=True),
        ),
    ]
