# Generated by Django 3.2.4 on 2021-09-25 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_alter_student_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='language',
            field=models.CharField(choices=[('E', 'English'), ('k', 'Kiswahili'), ('ki', 'Kinywaranda')], max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='nationality',
            field=models.CharField(choices=[('K', 'Kenyan'), ('U', 'Ugandan'), ('R', 'Rwandan')], max_length=23, null=True),
        ),
    ]
